services:
  app:
    build:
      context: .
      args:
        - ENVIRONMENT=dev
    ports:
      - "5000:5000"
    volumes:
      - ./src:/src
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SECRET_KEY=dev_secret_key
      - DEBUG=True
      - DB_ENGINE=mysql+pymysql
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=subscription_dev_db
      - JWT_SECRET_KEY=dev_jwt_secret_key
      - PYTHONPATH=/src
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "cd /src && python app.py"
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=subscription_dev_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: 