services:
  app:
    build:
      context: .
      args:
        - ENVIRONMENT=dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SECRET_KEY=dev_secret_key
      - DEBUG=True
      - DB_ENGINE=mysql+pymysql
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=subscription_dev_db
      - JWT_SECRET_KEY=dev_jwt_secret_key
    depends_on:
      - db
    command: >
      sh -c "flask run --host=0.0.0.0 --debug"
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=subscription_dev_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: 