services:
  test-app:
    build:
      context: .
      args:
        - ENVIRONMENT=test
    ports:
      - "5001:5000"
    volumes:
      - ./src:/src
      - ./tests:/tests
      - ./pytest.ini:/pytest.ini
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=testing
      - SECRET_KEY=test_secret_key
      - DEBUG=True
      - DB_ENGINE=mysql+pymysql
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=test-db
      - DB_PORT=3306
      - DB_NAME=subscription_test_db
      - JWT_SECRET_KEY=test_jwt_secret_key
      - TEST_CASE=${TEST_CASE:-""}
      - PYTEST_ARGS=${PYTEST_ARGS:-""}
      - PYTHONPATH=/src:/tests
    depends_on:
      test-db:
        condition: service_healthy
    # command: >
    #   sh -c "cd /src && pytest -v ${PYTEST_ARGS} ${TEST_CASE:-/tests/}"
    # infinite loop command
    command: >
      sh -c "while true; do sleep 1; done"
    networks:
      - test-network

  test-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=subscription_test_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 1.5s
      timeout: 3s
      retries: 30

networks:
  test-network:
    driver: bridge
