"""Add composite index for JOIN operations optimization

Revision ID: 7e0eb2c424f1
Revises: 045444694e5d
Create Date: 2024-05-04 17:49:09.353644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e0eb2c424f1'
down_revision = '045444694e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.alter_column('interval',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_index('idx_subscription_plan_duration')
        batch_op.drop_index('idx_subscription_plan_interval')
        batch_op.drop_index('idx_subscription_plan_interval_status')

    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index('idx_token_blacklist_expires_at')

    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.drop_index('idx_user_subscription_canceled_at')
        batch_op.drop_index('idx_user_subscription_payment_status')
        batch_op.drop_index('idx_user_subscription_plan_id')
        batch_op.drop_index('idx_user_subscription_renewal')
        batch_op.drop_index('idx_user_subscription_start_date')
        batch_op.drop_index('idx_user_subscription_status')
        batch_op.drop_index('idx_user_subscription_trial_end')
        batch_op.drop_index('idx_user_subscription_user_id')
        batch_op.drop_index('idx_user_subscription_user_plan')
        batch_op.create_index('idx_user_subscription_status_period_end', ['status', 'current_period_end'], unique=False)
        batch_op.create_index('idx_user_subscription_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index('idx_user_subscriptions_plan_join', ['user_id', 'plan_id', 'status'], unique=False)
        batch_op.create_index('idx_user_subscriptions_status_current_period_end', ['status', 'current_period_end'], unique=False)
        batch_op.create_index('idx_user_subscriptions_status_end_date', ['status', 'end_date'], unique=False)
        batch_op.create_index('idx_user_subscriptions_user_id_status', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.drop_index('idx_user_subscriptions_user_id_status')
        batch_op.drop_index('idx_user_subscriptions_status_end_date')
        batch_op.drop_index('idx_user_subscriptions_status_current_period_end')
        batch_op.drop_index('idx_user_subscriptions_plan_join')
        batch_op.drop_index('idx_user_subscription_user_status')
        batch_op.drop_index('idx_user_subscription_status_period_end')
        batch_op.create_index('idx_user_subscription_user_plan', ['user_id', 'plan_id'], unique=False)
        batch_op.create_index('idx_user_subscription_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_user_subscription_trial_end', ['trial_end_date'], unique=False)
        batch_op.create_index('idx_user_subscription_status', ['status'], unique=False)
        batch_op.create_index('idx_user_subscription_start_date', ['start_date'], unique=False)
        batch_op.create_index('idx_user_subscription_renewal', ['auto_renew', 'current_period_end'], unique=False)
        batch_op.create_index('idx_user_subscription_plan_id', ['plan_id'], unique=False)
        batch_op.create_index('idx_user_subscription_payment_status', ['payment_status'], unique=False)
        batch_op.create_index('idx_user_subscription_canceled_at', ['canceled_at'], unique=False)

    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index('idx_token_blacklist_expires_at', ['expires_at'], unique=False)

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.create_index('idx_subscription_plan_interval_status', ['interval', 'status'], unique=False)
        batch_op.create_index('idx_subscription_plan_interval', ['interval'], unique=False)
        batch_op.create_index('idx_subscription_plan_duration', ['duration_months'], unique=False)
        batch_op.alter_column('interval',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
