"""enhance_subscription_plan_model

Revision ID: b025fe21105a
Revises: 83cbf1e6393b
Create Date: 2025-04-28 11:22:33.995031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b025fe21105a'
down_revision = '83cbf1e6393b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interval', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('duration_months', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('max_users', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_subscription_plans_name')
        batch_op.create_index('idx_subscription_plan_parent', ['parent_id'], unique=False)
        batch_op.create_index('idx_subscription_plan_price', ['price'], unique=False)
        batch_op.create_index('idx_subscription_plan_public', ['is_public'], unique=False)
        batch_op.create_index('idx_subscription_plan_sort', ['sort_order'], unique=False)
        batch_op.create_index('idx_subscription_plan_status', ['status'], unique=False)
        batch_op.create_unique_constraint('uix_plan_name_interval', ['name', 'interval'])
        batch_op.create_foreign_key(None, 'subscription_plans', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uix_plan_name_interval', type_='unique')
        batch_op.drop_index('idx_subscription_plan_status')
        batch_op.drop_index('idx_subscription_plan_sort')
        batch_op.drop_index('idx_subscription_plan_public')
        batch_op.drop_index('idx_subscription_plan_price')
        batch_op.drop_index('idx_subscription_plan_parent')
        batch_op.create_index('ix_subscription_plans_name', ['name'], unique=True)
        batch_op.drop_column('sort_order')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('max_users')
        batch_op.drop_column('is_public')
        batch_op.drop_column('status')
        batch_op.drop_column('duration_months')
        batch_op.drop_column('interval')

    # ### end Alembic commands ###
