"""enhance_user_subscription_model

Revision ID: b65383a05fd4
Revises: e0e6bd486f06
Create Date: 2025-04-30 11:38:00.943050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65383a05fd4'
down_revision = 'e0e6bd486f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('canceled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_period_start', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('current_period_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('auto_renew', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('subscription_metadata', sa.Text(), nullable=True))
        batch_op.create_index('idx_user_subscription_cancel_period_end', ['cancel_at_period_end', 'current_period_end'], unique=False)
        batch_op.create_index('idx_user_subscription_current_period', ['current_period_start', 'current_period_end'], unique=False)
        batch_op.create_index('idx_user_subscription_payment', ['payment_status'], unique=False)
        batch_op.create_index('idx_user_subscription_renewal', ['auto_renew', 'current_period_end'], unique=False)
        batch_op.create_index('idx_user_subscription_trial_end', ['trial_end_date'], unique=False)
        batch_op.create_index('idx_user_subscription_trial_status', ['status', 'trial_end_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.drop_index('idx_user_subscription_trial_status')
        batch_op.drop_index('idx_user_subscription_trial_end')
        batch_op.drop_index('idx_user_subscription_renewal')
        batch_op.drop_index('idx_user_subscription_payment')
        batch_op.drop_index('idx_user_subscription_current_period')
        batch_op.drop_index('idx_user_subscription_cancel_period_end')
        batch_op.drop_column('subscription_metadata')
        batch_op.drop_column('auto_renew')
        batch_op.drop_column('cancel_at_period_end')
        batch_op.drop_column('quantity')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('current_period_end')
        batch_op.drop_column('current_period_start')
        batch_op.drop_column('canceled_at')
        batch_op.drop_column('trial_end_date')

    # ### end Alembic commands ###
